# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test-integration
- compile-documentation

test-frontend:
  stage: test-integration
  image: node
  script:
    - cd frontend/
    - npm install
    - npm test -- --watchAll=false

test-backend:
  stage: test-integration
  image: fedora
  before_script:
    - dnf install -y python3 python3-pip dotnet dotnet-sdk-6.0 procps-ng
    - pip3 install -r backend-testing/requirements.txt

  script:
    - cd backend/
    - ASPNETCORE_ENVIRONMENT=Development dotnet build backend.sln
    - ASPNETCORE_URLS=https://localhost:7220 ASPNETCORE_ENVIRONMENT=Development dotnet run > backend.log &
    - cd ../backend-testing
    - python3 main.py https://localhost:7220 | tee backend-testing.log
    - pkill -15 dotnet

  artifacts:
    paths:
      - backend/backend.log
      - backend-testing/backend-testing.log

jsdocs-frontend:
  stage: compile-documentation
  image: node
  script:
    - cd frontend/src/
    - npm run docs
  artifacts:
    paths:
      - frontend/docs

doxygen-backend:
  stage: compile-documentation
  image: fedora
  before_script:
    - dnf install -y doxygen doxygen-latex make
  script:
    - cd backend/
    - doxygen .doxygen
    - cd docs/latex
    - make
  artifacts:
    paths:
      - backend/docs
      - backend/docs/latex/refman.pdf
