version: "3.9"

services:
  backend:
    build: backend/
    restart: always
    volumes:
      - backend_data:/app/data
  frontend:
    build: frontend/
    restart: always
  nginx:
    build: nginx/
    restart: always
    ports:
      - "80:80"
volumes:
    backend_data: {}